# Generated by Django 3.2.5 on 2021-07-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0006_address_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='area',
            field=models.CharField(blank=True, choices=[('Antrim', 'Clare'), ('Cork', 'Dublin'), ('Galway', 'Kerry'), ('Kildare', 'Kilkenny'), ('Limerick', 'Sligo'), ('Tipperary', 'Mayo'), ('Louth', 'Longford')], max_length=100, null=True),
        ),
    ]
